classes: {
  business-actor: {
    icon: ./icons/business_actor.svg {near: top-right}
    width: 200
    height: 50
    style: {
      fill: "#FFFFBD"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  business-interface: {
    icon: ./icons/business_interface.svg
    width: 200
    height: 50
    style: {
      fill: "#FFFFBD"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  business-function: {
    icon: ./icons/business_function.svg
    width: 200
    height: 50
    style: {
      fill: "#FFFFBD"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  business-process: {
    icon: ./icons/business_process.svg
    width: 200
    height: 50
    style: {
      fill: "#FFFFBD"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  application-interface: {
    icon: ./icons/application_interface.svg
    width: 200
    height: 50
    style: {
      fill: "#C5FDFE"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  application-function: {
    icon: ./icons/application_function.svg
    width: 200
    height: 50
    style: {
      fill: "#C5FDFE"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  application-process: {
    icon: ./icons/application_process.svg
    width: 200
    height: 50
    style: {
      fill: "#C5FDFE"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  technology-interface: {
    icon: ./icons/technology_interface.svg
    width: 200
    height: 50
    style: {
      fill: "#CFE6BB"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  technology-function: {
    icon: ./icons/technology_function.svg
    width: 200
    height: 50
    style: {
      fill: "#CFE6BB"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  technology-process: {
    icon: ./icons/technology_process.svg
    width: 200
    height: 50
    style: {
      fill: "#CFE6BB"
      stroke-width: 1
      shadow: true
      border-radius: 5
    }
  }

  rel-composition: {
    target-arrowhead: {
      shape: diamond
      style.filled: true
    }
  }

  rel-aggregation: {
    target-arrowhead: {
      shape: diamond
      style.filled: false
    }
  }
  
  rel-assignment: {
    source-arrowhead.shape: circle
    target-arrowhead.shape: circle
  }

  rel-specialization: {
    target-arrowhead: {
      shape: triangle
      style.filled: false
    }
  }

  rel-realization: {
    target-arrowhead: {
      shape: triangle
      style.filled: false
    }
    style.stroke-dash: 3
  }

  rel-used-by {
    target-arrowhead: {
      shape: arrow
    }
  }

  rel-access {
    target-arrowhead: {
      shape: arrow
    }
    style.stroke-dash: 2
  }

  rel-association {
    source-arrowhead.shape: none
    target-arrowhead.shape: none
  }

  rel-triggering {
    target-arrowhead {
      shape: triangle
      style.filled: true
    }
  }

  rel-flow {
    target-arrowhead {
      shape: triangle
      style.filled: true
    }
    style.stroke-dash: 4
  }
}

